### ISSUE TITLE
Is there a CPU inference version for this code？

### ISSUE THREAD

**Issue by AlexQie** [dannysdeng/EnhanceGAN#1]
Thank you for releasing this wonderful code, but I have some troubles when install the GPU touch on my server (without root privilege). I have tried run this code on my Mac but failed. Could you please release a CPU inference version ?

**Comment by dannysdeng** [comment]
Hi Alex. We updated the code a while ago, see if the following works in your environment setup.

> For CPU mode, use "--gpu 0"  in ./run_single_image.sh

**Comment by AlexQie** [comment]
Yeah, I have pulled new code and run ./run_single_image.sh again. But I got the error massage:
`torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
	[C]: in function 'error'
	...uang/software/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	...uang/software/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...guang/software/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...uang/software/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...uang/software/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	./run_single.lua:116: in main chunk
	[C]: in function 'dofile'
	...ware/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0100238330`
I have searched this error, and it seems that the model is GPU version. Like [this](https://github.com/OpenNMT/OpenNMT/issues/53#issuecomment-270908477) code base, the author released a script to convert model to CPU version. I am not familiar with torch, and this is a bit of tricky...

**Comment by dannysdeng** [comment]
We've created a CPU version of the model. You can pull the code again and download "model_best_cpu.t7" ([URL1](https://drive.google.com/open?id=13ay08vLY2OezNbDxj-nSMRGcMy2qW8z6) or [URL2](https://pan.baidu.com/disk/home#/all?vmode=list&path=%2FACMMM18_EnhanceGAN)) and see if it works with your environment setup. 

And as you might guess, the "model_best_cpu.t7" file should be put in the "checkpoints" folder.

**Comment by AlexQie** [comment]
OK!! Thanks!!! It works well.
