### ISSUE TITLE
Error when trying to run on a single image.

### ISSUE THREAD

**Issue by akh64bit** [dannysdeng/EnhanceGAN#4]
I am trying to run the code on a single image as mentioned in the README page.
I have not changed anything. Here is the error that I am getting.

`/home/ak/torch/install/bin/luajit: /home/ak/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
...all/share/lua/5.1/stn/AffineTransformMatrixGenerator.lua:54: Expected 3 parameters, got 4
stack traceback:
	[C]: in function 'assert'
	...all/share/lua/5.1/stn/AffineTransformMatrixGenerator.lua:54: in function 'check'
	...all/share/lua/5.1/stn/AffineTransformMatrixGenerator.lua:77: in function 'func'
	/home/ak/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/home/ak/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function </home/ak/torch/install/share/lua/5.1/nngraph/gmodule.lua:300>
	[C]: in function 'xpcall'
	/home/ak/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/ak/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./run_single.lua:150: in main chunk
	[C]: in function 'dofile'
	...e/ak/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x55b326cbfef0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/ak/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/ak/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./run_single.lua:150: in main chunk
	[C]: in function 'dofile'
	...e/ak/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x55b326cbfef0
Output saved to ./demo_result/`
``

Any clue what could be wrong?

Thanks.

**Comment by dannysdeng** [comment]
Hi,

Is the file in your path "/home/ak/torch/install/share/lua/5.1/stn/AffineTransformMatrixGenerator.lua" the same as the one as this repo? 

(meaning whether you have copied successfully the files in the "stn" folder to the Torch directory? Sometimes it requires root permission based on different system setups)

**Comment by akh64bit** [comment]
Thanks Danny,
you are right. Some files were not copied properly :)
It is working now.
